### ISSUE TITLE
Behaviour of `--scroll` unclear [?]

### ISSUE THREAD

**Issue by padolsey** [lennym/timeliner#22]
This library is amazing! Really great work and exactly what I was looking for :)

I tried it out using  the `--scroll` flag:

```bash
timeliner http://bbc.co.uk --sleep 5000 --scroll
```

But this appears to just very quickly go between a scroll-offset of zero and one (which makes sense when looking at the [code](https://github.com/lennym/timeliner/blob/4b47024f8215fbcbaaa13f63125a264271806a09/lib/page.js#L25): it calls `scrollBy(0,1)` and `scrollBy(0,-1)` repeatedly). Is this the intended behaviour?

**Comment by lennym** [comment]
Crudely, yes it is intended behaviour. More generally it's probably not desirable behaviour.

The library has mostly just been used so far (afaik) by my team internally, so has evolved as per our needs, which were to measure fps changes over the load lifecycle on particular sites. As so the 1px scroll was just to force `requestAnimationFrame` to fire, and so to give meaningful data, but without hitting any lazy loading effects on the sites we were testing.

In a broader use case, I think this flag would be better used to specify a continuous scroll speed, rather than the stationary vibration that's going on at the moment.

**Comment by padolsey** [comment]
Ah understood. I think that's a fair behaviour, though perhaps could be named something like `--force-raf` or similar (and then, as you said, `--scroll` can be used to define scrolling speed). For now I'm gonna try getting the scrolling behaviour I'm after by using `inject` anyway, so all is good. 👍

**Comment by lennym** [comment]
I've updated a little bit to similar effect. I'd be keen to know your thoughts.

https://github.com/lennym/timeliner/pull/23
